# Generated by Django 5.0.4 on 2024-04-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='Exercise_Level',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='pets',
            name='Happiness_Level',
            field=models.CharField(default='Happy', max_length=50),
        ),
        migrations.AlterField(
            model_name='pets',
            name='Health_Status',
            field=models.CharField(default='Healthy', max_length=50),
        ),
        migrations.AlterField(
            model_name='pets',
            name='Hunger_Level',
            field=models.CharField(default='Full', max_length=50),
        ),
        migrations.AlterField(
            model_name='pets',
            name='Hygiene_Level',
            field=models.CharField(default='clean', max_length=50),
        ),
    ]
