# Generated by Django 5.0.4 on 2024-05-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_alter_pets_exercise_level_alter_pets_happiness_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_pets',
            fields=[
                ('PetID', models.AutoField(primary_key=True, serialize=False)),
                ('Pet_Name', models.CharField(max_length=50)),
                ('Species', models.CharField(max_length=50)),
                ('Breed', models.CharField(max_length=50)),
                ('Age', models.PositiveIntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Health_Status', models.CharField(default='Healthy', max_length=50)),
                ('Happiness_Level', models.CharField(default='Happy', max_length=50)),
                ('Hunger_Level', models.CharField(default='Full', max_length=50)),
                ('Hygiene_Level', models.CharField(default='clean', max_length=50)),
                ('Exercise_Level', models.CharField(default='Active', max_length=50)),
            ],
        ),
    ]
